check root user for dse_ip_port_status, ip_port_process_count, and ip_port_process_list

diff --git a/ip_port_process_count b/ip_port_process_count
--- a/ip_port_process_count
+++ b/ip_port_process_count
@@ -4,6 +4,9 @@
 # Show number of processes that have the port open
 #
 
+# make sure running as root
+if [[ $EUID -ne 0 ]]; then echo "Error: Run $(basename $0) as root"; exit 1; fi
+
 if [ x$1 = x ]; then echo "`basename $0`: Internal error. ShowPort missing port arg"; exit; fi
 portNumber="$1"; shift
 
diff --git a/ip_port_process_list b/ip_port_process_list
--- a/ip_port_process_list
+++ b/ip_port_process_list
@@ -4,6 +4,9 @@
 # List processes that have the port open
 #
 
+# make sure running as root
+if [[ $EUID -ne 0 ]]; then echo "Error: Run $(basename $0) as root"; exit 1; fi
+
 OS_FLAVOR=$(os_flavor)
 
 if [ x$1 = x ]; then echo "`basename $0`: Error - Missing port arg"; exit; fi
