solr_index_download/solr_index_upload_and_reindex - automatically determine node IP address and check for schema.xml existance.

diff --git a/solr_index_upload_and_reindex b/solr_index_upload_and_reindex
--- a/solr_index_upload_and_reindex
+++ b/solr_index_upload_and_reindex
@@ -8,15 +8,18 @@ user=":"
 #user="myuser"
 #user="myuser:mypassword"
 
-ipaddr=`ip_address_private`
-#ipaddr="56.76.80.64"
+ipaddr=$(ip_address_private)
+#ipaddr="56.79.80.64"
 
 core="x.y"
 #core="mykeyspace.mytable"
 
+schemafile=schema.xml
+if [ ! -f "$schemafile" ]; then echo "$schemafile: file not found"; exit -1; fi
+
 deleteAll=true         # If healthy live production deleteAll=false to let old indexes run until reindexed, If node badly broken use deleteAll=true to discard old indexes
 
-echo $ipaddr, $core, deleteAll=$deleteAll >&2
+echo $ipaddr, $core, $schemafile, deleteAll=$deleteAll >&2
 answer=`printf '%s' 'Parameters OK? ' >&2; read val; echo $val;`;
 if [ x$answer != x"yes" ]; then echo cancelled >&2; exit 1; fi
 
